"""Human-readable semantic definitions for the Gold metadata catalog.

Keep this file focused on business meaning: tables, column descriptions,
metrics, and safe joins. The builder logic lives in gold.metadata.
"""

from gold.config import (
    DAILY_BRAND_SUMMARY,
    DAILY_CATEGORY_SUMMARY,
    DAILY_EVENT_SUMMARY,
    DAILY_PRODUCT_SUMMARY,
    DIM_PRODUCT,
    DIM_SESSION,
    DIM_TIME,
    DIM_USER,
    FACT_EVENTS,
    FACT_SALES,
    STG_EVENTS,
)

# Table-level semantic definitions published to metadata.table_catalog.
TABLE_DEFINITIONS = [
    {
        "table": STG_EVENTS,
        "namespace_role": "staging",
        "layer": "gold_staging",
        "table_type": "staging",
        "business_name": "Staging events",
        "description": "Clean deduplicated events prepared for Gold tables.",
        "grain": "1 row = 1 deduplicated valid event from Silver",
        "primary_key": "event_fingerprint",
        "unique_key": "event_fingerprint",
        "is_agent_visible": False,
        "recommended_for_agent": False,
    },
    {
        "table": FACT_EVENTS,
        "namespace_role": "gold",
        "layer": "gold",
        "table_type": "fact",
        "business_name": "Event fact",
        "description": "Detailed ecommerce events with event-type flags.",
        "grain": "1 row = 1 unique business event",
        "primary_key": "event_fingerprint",
        "unique_key": "event_fingerprint",
        "is_agent_visible": True,
        "recommended_for_agent": False,
    },
    {
        "table": FACT_SALES,
        "namespace_role": "gold",
        "layer": "gold",
        "table_type": "fact",
        "business_name": "Sales fact",
        "description": "Purchase events represented as sales rows.",
        "grain": "1 row = 1 purchase event",
        "primary_key": "sale_id",
        "unique_key": "sale_id",
        "is_agent_visible": True,
        "recommended_for_agent": True,
    },
    {
        "table": DIM_TIME,
        "namespace_role": "gold",
        "layer": "gold",
        "table_type": "dimension",
        "business_name": "Time dimension",
        "description": "Hourly event time attributes.",
        "grain": "1 row = 1 event hour",
        "primary_key": "time_id",
        "unique_key": "time_id",
        "is_agent_visible": True,
        "recommended_for_agent": True,
    },
    {
        "table": DIM_PRODUCT,
        "namespace_role": "gold",
        "layer": "gold",
        "table_type": "dimension",
        "business_name": "Product dimension",
        "description": "Product category, brand, and observed price attributes.",
        "grain": "1 row = 1 product",
        "primary_key": "product_id",
        "unique_key": "product_id",
        "is_agent_visible": True,
        "recommended_for_agent": True,
    },
    {
        "table": DIM_USER,
        "namespace_role": "gold",
        "layer": "gold",
        "table_type": "dimension",
        "business_name": "User dimension",
        "description": "User activity and purchase summary.",
        "grain": "1 row = 1 user",
        "primary_key": "user_id",
        "unique_key": "user_id",
        "is_agent_visible": True,
        "recommended_for_agent": True,
    },
    {
        "table": DIM_SESSION,
        "namespace_role": "gold",
        "layer": "gold",
        "table_type": "dimension",
        "business_name": "Session dimension",
        "description": "Session behavior and revenue summary.",
        "grain": "1 row = 1 session",
        "primary_key": "session_id",
        "unique_key": "session_id",
        "is_agent_visible": True,
        "recommended_for_agent": True,
    },
    {
        "table": DAILY_EVENT_SUMMARY,
        "namespace_role": "gold",
        "layer": "gold",
        "table_type": "summary",
        "business_name": "Daily event summary",
        "description": "Daily traffic, conversion, and revenue metrics.",
        "grain": "1 row = 1 event_date",
        "primary_key": "event_date",
        "unique_key": "event_date",
        "is_agent_visible": True,
        "recommended_for_agent": True,
    },
    {
        "table": DAILY_PRODUCT_SUMMARY,
        "namespace_role": "gold",
        "layer": "gold",
        "table_type": "summary",
        "business_name": "Daily product summary",
        "description": "Daily metrics by product, brand, and category.",
        "grain": "1 row = 1 event_date + 1 product",
        "primary_key": "summary_id",
        "unique_key": "event_date, product_id",
        "is_agent_visible": True,
        "recommended_for_agent": True,
    },
    {
        "table": DAILY_CATEGORY_SUMMARY,
        "namespace_role": "gold",
        "layer": "gold",
        "table_type": "summary",
        "business_name": "Daily category summary",
        "description": "Daily metrics by category hierarchy.",
        "grain": "1 row = 1 event_date + category hierarchy",
        "primary_key": "summary_id",
        "unique_key": "event_date, category_l1, category_l2, category_l3",
        "is_agent_visible": True,
        "recommended_for_agent": True,
    },
    {
        "table": DAILY_BRAND_SUMMARY,
        "namespace_role": "gold",
        "layer": "gold",
        "table_type": "summary",
        "business_name": "Daily brand summary",
        "description": "Daily metrics by brand.",
        "grain": "1 row = 1 event_date + brand",
        "primary_key": "summary_id",
        "unique_key": "event_date, brand",
        "is_agent_visible": True,
        "recommended_for_agent": True,
    },
]

# Common column metadata applies by column name across all tables.
COLUMN_METADATA_BY_NAME = {
    "event_fingerprint": {
        "business_name": "Event fingerprint",
        "description": "Stable event key used to deduplicate events.",
        "is_join_key": True,
        "is_unique_key": True,
        "agent_synonyms": "mã sự kiện, khóa sự kiện",
    },
    "source_event_id": {
        "business_name": "Source event id",
        "description": "Original source event id.",
        "is_dimension": True,
    },
    "sale_id": {
        "business_name": "Sale id",
        "description": "Unique sale row id.",
        "is_unique_key": True,
        "agent_synonyms": "mã giao dịch mua",
    },
    "summary_id": {
        "business_name": "Summary id",
        "description": "Unique summary row id.",
        "is_unique_key": True,
    },
    "time_id": {
        "business_name": "Time id",
        "description": "Hourly time key in yyyyMMddHH format.",
        "is_time_column": True,
        "is_join_key": True,
        "agent_synonyms": "giờ, khóa thời gian",
    },
    "event_ts": {
        "business_name": "Event timestamp",
        "description": "Timestamp when the event happened.",
        "is_time_column": True,
        "agent_synonyms": "thời điểm sự kiện",
    },
    "sale_ts": {
        "business_name": "Sale timestamp",
        "description": "Timestamp when the purchase event happened.",
        "is_time_column": True,
        "agent_synonyms": "thời điểm mua",
    },
    "event_date": {
        "business_name": "Event date",
        "description": "Calendar date of the event.",
        "is_dimension": True,
        "is_time_column": True,
        "agent_synonyms": "ngày, ngày sự kiện",
    },
    "sale_date": {
        "business_name": "Sale date",
        "description": "Calendar date of the purchase event.",
        "is_dimension": True,
        "is_time_column": True,
        "agent_synonyms": "ngày mua, ngày bán",
    },
    "event_year": {
        "business_name": "Event year",
        "description": "Year of the event.",
        "is_dimension": True,
        "is_time_column": True,
    },
    "event_month": {
        "business_name": "Event month",
        "description": "Month of the event.",
        "is_dimension": True,
        "is_time_column": True,
    },
    "event_day": {
        "business_name": "Event day",
        "description": "Day of month of the event.",
        "is_dimension": True,
        "is_time_column": True,
    },
    "event_hour": {
        "business_name": "Event hour",
        "description": "Hour of day of the event.",
        "is_dimension": True,
        "is_time_column": True,
    },
    "event_type": {
        "business_name": "Event type",
        "description": "User behavior type for the event.",
        "is_dimension": True,
        "example_values": "view, cart, remove_from_cart, purchase",
        "allowed_values": "view, cart, remove_from_cart, purchase",
        "agent_synonyms": "loại sự kiện, hành vi",
    },
    "product_id": {
        "business_name": "Product id",
        "description": "Product key.",
        "is_dimension": True,
        "is_join_key": True,
        "agent_synonyms": "sản phẩm, mã sản phẩm",
    },
    "category_id": {
        "business_name": "Category id",
        "description": "Source category id.",
        "is_dimension": True,
        "agent_synonyms": "mã danh mục",
    },
    "category_code": {
        "business_name": "Category code",
        "description": "Source category code.",
        "is_dimension": True,
        "agent_synonyms": "mã ngành hàng, mã danh mục",
    },
    "category_l1": {
        "business_name": "Category level 1",
        "description": "Top-level product category.",
        "is_dimension": True,
        "agent_synonyms": "danh mục, ngành hàng, loại sản phẩm",
    },
    "category_l2": {
        "business_name": "Category level 2",
        "description": "Second-level product category.",
        "is_dimension": True,
        "agent_synonyms": "danh mục, ngành hàng, loại sản phẩm",
    },
    "category_l3": {
        "business_name": "Category level 3",
        "description": "Third-level product category.",
        "is_dimension": True,
        "agent_synonyms": "danh mục, ngành hàng, loại sản phẩm",
    },
    "brand": {
        "business_name": "Brand",
        "description": "Product brand.",
        "is_dimension": True,
        "example_values": "unknown",
        "agent_synonyms": "thương hiệu, hãng",
    },
    "user_id": {
        "business_name": "User id",
        "description": "User key.",
        "is_dimension": True,
        "is_join_key": True,
        "agent_synonyms": "người dùng, khách hàng",
    },
    "session_id": {
        "business_name": "Session id",
        "description": "User session key.",
        "is_dimension": True,
        "is_join_key": True,
        "agent_synonyms": "phiên, phiên truy cập",
    },
    "price": {
        "business_name": "Event price",
        "description": "Observed product price on the event.",
        "is_metric": True,
        "unit": "currency",
        "agent_synonyms": "giá, giá sự kiện",
    },
    "unit_price": {
        "business_name": "Unit price",
        "description": "Unit price for a purchase event.",
        "is_metric": True,
        "agent_synonyms": "đơn giá, giá bán",
    },
    "gross_amount": {
        "business_name": "Gross amount",
        "description": "Purchase amount before adjustments.",
        "is_metric": True,
        "agent_synonyms": "doanh thu, tiền bán",
    },
    "quantity": {
        "business_name": "Quantity",
        "description": "Purchase quantity; current event data uses 1.",
        "is_metric": True,
        "agent_synonyms": "số lượng",
    },
    "revenue": {
        "business_name": "Revenue",
        "description": "Revenue at the table grain.",
        "is_metric": True,
        "agent_synonyms": "doanh thu, tổng doanh thu, tiền bán",
    },
    "total_revenue": {
        "business_name": "Total revenue",
        "description": "Total revenue at the table grain.",
        "is_metric": True,
        "agent_synonyms": "doanh thu, tổng doanh thu, tiền bán",
    },
    "view_count": {
        "business_name": "View count",
        "description": "Number of view events.",
        "is_metric": True,
        "agent_synonyms": "lượt xem, số lượt xem",
    },
    "total_views": {
        "business_name": "Total views",
        "description": "Total number of view events.",
        "is_metric": True,
        "agent_synonyms": "lượt xem, số lượt xem",
    },
    "cart_count": {
        "business_name": "Cart count",
        "description": "Number of add-to-cart events.",
        "is_metric": True,
        "agent_synonyms": "lượt thêm giỏ, số lượt thêm vào giỏ",
    },
    "total_carts": {
        "business_name": "Total carts",
        "description": "Total number of add-to-cart events.",
        "is_metric": True,
        "agent_synonyms": "lượt thêm giỏ, số lượt thêm vào giỏ",
    },
    "purchase_count": {
        "business_name": "Purchase count",
        "description": "Number of purchase events.",
        "is_metric": True,
        "agent_synonyms": "lượt mua, số lượt mua, số giao dịch mua",
    },
    "total_purchases": {
        "business_name": "Total purchases",
        "description": "Total number of purchase events.",
        "is_metric": True,
        "agent_synonyms": "lượt mua, số lượt mua, số giao dịch mua",
    },
    "remove_from_cart_count": {
        "business_name": "Remove from cart count",
        "description": "Number of remove-from-cart events.",
        "is_metric": True,
        "agent_synonyms": "lượt bỏ giỏ, số lượt bỏ khỏi giỏ",
    },
    "total_remove_from_carts": {
        "business_name": "Total remove from carts",
        "description": "Total number of remove-from-cart events.",
        "is_metric": True,
        "agent_synonyms": "lượt bỏ giỏ, số lượt bỏ khỏi giỏ",
    },
    "total_cart_adds": {
        "business_name": "Total cart adds",
        "description": "Total add-to-cart events for the user.",
        "is_metric": True,
        "agent_synonyms": "lượt thêm giỏ, số lượt thêm vào giỏ",
    },
    "conversion_rate": {
        "business_name": "Conversion rate",
        "description": "Purchases divided by views.",
        "is_metric": True,
        "agent_synonyms": "tỷ lệ chuyển đổi",
    },
    "cart_to_purchase_rate": {
        "business_name": "Cart to purchase rate",
        "description": "Purchases divided by add-to-cart events.",
        "is_metric": True,
        "agent_synonyms": "tỷ lệ giỏ hàng sang mua",
    },
    "unique_users": {
        "business_name": "Unique users",
        "description": "Distinct users at the table grain.",
        "is_metric": True,
        "agent_synonyms": "người dùng, khách hàng, số khách hàng",
    },
    "unique_sessions": {
        "business_name": "Unique sessions",
        "description": "Distinct sessions at the table grain.",
        "is_metric": True,
        "agent_synonyms": "phiên, phiên truy cập, số phiên",
    },
    "unique_products": {
        "business_name": "Unique products",
        "description": "Distinct products at the table grain.",
        "is_metric": True,
        "agent_synonyms": "sản phẩm, số sản phẩm",
    },
    "unique_events": {
        "business_name": "Unique events",
        "description": "Distinct events at the table grain.",
        "is_metric": True,
    },
    "total_events": {
        "business_name": "Total events",
        "description": "Total number of events.",
        "is_metric": True,
        "agent_synonyms": "số sự kiện, lượt sự kiện",
    },
    "event_count": {
        "business_name": "Event count",
        "description": "Number of events.",
        "is_metric": True,
        "agent_synonyms": "số sự kiện, lượt sự kiện",
    },
    "avg_event_price": {
        "business_name": "Average event price",
        "description": "Average observed event price.",
        "is_metric": True,
        "agent_synonyms": "giá trung bình",
    },
    "avg_price": {
        "business_name": "Average price",
        "description": "Average observed price.",
        "is_metric": True,
        "agent_synonyms": "giá trung bình",
    },
    "min_price": {
        "business_name": "Minimum price",
        "description": "Minimum observed price.",
        "is_metric": True,
    },
    "max_price": {
        "business_name": "Maximum price",
        "description": "Maximum observed price.",
        "is_metric": True,
    },
    "avg_observed_price": {
        "business_name": "Average observed price",
        "description": "Average observed product price.",
        "is_metric": True,
    },
    "min_observed_price": {
        "business_name": "Minimum observed price",
        "description": "Minimum observed product price.",
        "is_metric": True,
    },
    "max_observed_price": {
        "business_name": "Maximum observed price",
        "description": "Maximum observed product price.",
        "is_metric": True,
    },
    "record_count": {
        "business_name": "Record count",
        "description": "Number of source records behind this dimension row.",
        "is_metric": True,
    },
    "total_sessions": {
        "business_name": "Total sessions",
        "description": "Total sessions for the user.",
        "is_metric": True,
        "agent_synonyms": "số phiên, phiên truy cập",
    },
    "session_duration_sec": {
        "business_name": "Session duration seconds",
        "description": "Session duration in seconds.",
        "is_metric": True,
    },
    "session_revenue": {
        "business_name": "Session revenue",
        "description": "Revenue generated in the session.",
        "is_metric": True,
        "agent_synonyms": "doanh thu, tiền bán",
    },
    "has_purchase": {
        "business_name": "Has purchase",
        "description": "True when the session contains a purchase.",
        "is_dimension": True,
    },
    "is_view": {
        "business_name": "Is view",
        "description": "True when event_type is view.",
        "is_metric": True,
    },
    "is_cart": {
        "business_name": "Is cart",
        "description": "True when event_type is cart.",
        "is_metric": True,
    },
    "is_remove_from_cart": {
        "business_name": "Is remove from cart",
        "description": "True when event_type is remove_from_cart.",
        "is_metric": True,
    },
    "is_purchase": {
        "business_name": "Is purchase",
        "description": "True when event_type is purchase.",
        "is_metric": True,
    },
    "first_seen_at": {
        "business_name": "First seen at",
        "description": "First observed event timestamp.",
        "is_time_column": True,
    },
    "last_seen_at": {
        "business_name": "Last seen at",
        "description": "Last observed event timestamp.",
        "is_time_column": True,
    },
    "session_start_at": {
        "business_name": "Session start at",
        "description": "First event timestamp in the session.",
        "is_time_column": True,
    },
    "session_end_at": {
        "business_name": "Session end at",
        "description": "Last event timestamp in the session.",
        "is_time_column": True,
    },
}

# Table-specific metadata overrides common metadata only where needed.
TABLE_SPECIFIC_COLUMN_METADATA = {
    STG_EVENTS: {
        "event_fingerprint": {
            "source_table": "silver.ecommerce_events",
            "source_column": "event_fingerprint",
            "transformation_logic": "Filter valid events and deduplicate by event_fingerprint.",
        },
        "session_id": {
            "source_table": "silver.ecommerce_events",
            "source_column": "user_session",
            "transformation_logic": "Rename user_session to session_id.",
        },
        "time_id": {
            "transformation_logic": "date_format(event_ts, 'yyyyMMddHH')",
        },
    },
    FACT_EVENTS: {
        "event_fingerprint": {
            "transformation_logic": "Selected from stg_events as the unique event key.",
        },
        "is_view": {"transformation_logic": "event_type = 'view'"},
        "is_cart": {"transformation_logic": "event_type = 'cart'"},
        "is_remove_from_cart": {
            "transformation_logic": "event_type = 'remove_from_cart'",
        },
        "is_purchase": {"transformation_logic": "event_type = 'purchase'"},
    },
    FACT_SALES: {
        "sale_id": {
            "source_column": "event_fingerprint",
            "transformation_logic": "Use purchase event_fingerprint as sale_id.",
        },
        "gross_amount": {
            "transformation_logic": "unit_price * quantity; quantity is 1 for event data.",
        },
    },
    DIM_TIME: {
        "time_id": {"description": "Primary hourly time key."},
        "day_of_week": {
            "business_name": "Day of week",
            "description": "Day of week number.",
            "is_dimension": True,
            "is_time_column": True,
        },
        "day_name": {
            "business_name": "Day name",
            "description": "Day of week name.",
            "is_dimension": True,
            "is_time_column": True,
        },
        "month_name": {
            "business_name": "Month name",
            "description": "Month name.",
            "is_dimension": True,
            "is_time_column": True,
        },
        "quarter": {
            "business_name": "Quarter",
            "description": "Calendar quarter.",
            "is_dimension": True,
            "is_time_column": True,
        },
        "is_weekend": {
            "business_name": "Is weekend",
            "description": "True for Saturday or Sunday.",
            "is_dimension": True,
        },
    },
    DIM_PRODUCT: {
        "product_id": {
            "description": "Primary product key.",
            "is_unique_key": True,
        },
    },
    DIM_USER: {
        "user_id": {
            "description": "Primary user key.",
            "is_unique_key": True,
        },
    },
    DIM_SESSION: {
        "session_id": {
            "description": "Primary session key.",
            "is_unique_key": True,
        },
    },
    DAILY_EVENT_SUMMARY: {
        "event_date": {
            "description": "Daily summary date.",
            "is_unique_key": True,
        },
    },
    DAILY_PRODUCT_SUMMARY: {
        "summary_id": {
            "description": "Unique key for event_date and product_id.",
        },
    },
    DAILY_CATEGORY_SUMMARY: {
        "summary_id": {
            "description": "Unique key for event_date and category hierarchy.",
        },
    },
    DAILY_BRAND_SUMMARY: {
        "summary_id": {
            "description": "Unique key for event_date and brand.",
        },
    },
}

METRIC_DEFINITIONS = [
    {
        "metric_name": "total_revenue",
        "business_name": "Total revenue",
        "description": "Revenue from purchase events.",
        "formula_sql": "SUM(total_revenue)",
        "base_table": DAILY_EVENT_SUMMARY,
        "default_time_column": "event_date",
        "aggregation_type": "sum",
        "unit": "currency",
        "example_question": "Doanh thu theo ngày là bao nhiêu?",
    },
    {
        "metric_name": "purchase_count",
        "business_name": "Purchase count",
        "description": "Number of purchase events.",
        "formula_sql": "SUM(total_purchases)",
        "base_table": DAILY_EVENT_SUMMARY,
        "default_time_column": "event_date",
        "aggregation_type": "sum",
        "unit": "events",
        "example_question": "Có bao nhiêu lượt mua mỗi ngày?",
    },
    {
        "metric_name": "view_count",
        "business_name": "View count",
        "description": "Number of view events.",
        "formula_sql": "SUM(total_views)",
        "base_table": DAILY_EVENT_SUMMARY,
        "default_time_column": "event_date",
        "aggregation_type": "sum",
        "unit": "events",
        "example_question": "Số lượt xem theo ngày là bao nhiêu?",
    },
    {
        "metric_name": "cart_count",
        "business_name": "Cart count",
        "description": "Number of add-to-cart events.",
        "formula_sql": "SUM(total_carts)",
        "base_table": DAILY_EVENT_SUMMARY,
        "default_time_column": "event_date",
        "aggregation_type": "sum",
        "unit": "events",
        "example_question": "Số lượt thêm giỏ theo ngày là bao nhiêu?",
    },
    {
        "metric_name": "remove_from_cart_count",
        "business_name": "Remove from cart count",
        "description": "Number of remove-from-cart events.",
        "formula_sql": "SUM(total_remove_from_carts)",
        "base_table": DAILY_EVENT_SUMMARY,
        "default_time_column": "event_date",
        "aggregation_type": "sum",
        "unit": "events",
        "example_question": "Có bao nhiêu lượt bỏ khỏi giỏ?",
    },
    {
        "metric_name": "conversion_rate",
        "business_name": "Conversion rate",
        "description": "Purchases divided by views.",
        "formula_sql": "CASE WHEN total_views = 0 THEN 0 ELSE total_purchases * 1.0 / total_views END",
        "base_table": DAILY_EVENT_SUMMARY,
        "default_time_column": "event_date",
        "aggregation_type": "ratio",
        "unit": "ratio",
        "example_question": "Tỷ lệ chuyển đổi theo ngày là bao nhiêu?",
    },
    {
        "metric_name": "cart_to_purchase_rate",
        "business_name": "Cart to purchase rate",
        "description": "Purchases divided by add-to-cart events.",
        "formula_sql": "CASE WHEN total_carts = 0 THEN 0 ELSE total_purchases * 1.0 / total_carts END",
        "base_table": DAILY_EVENT_SUMMARY,
        "default_time_column": "event_date",
        "aggregation_type": "ratio",
        "unit": "ratio",
        "example_question": "Tỷ lệ từ giỏ hàng sang mua là bao nhiêu?",
    },
    {
        "metric_name": "active_users",
        "business_name": "Active users",
        "description": "Distinct users with events.",
        "formula_sql": "COUNT(DISTINCT user_id)",
        "base_table": FACT_EVENTS,
        "default_time_column": "event_date",
        "aggregation_type": "count_distinct",
        "unit": "users",
        "example_question": "Có bao nhiêu khách hàng hoạt động?",
    },
    {
        "metric_name": "unique_sessions",
        "business_name": "Unique sessions",
        "description": "Distinct sessions with events.",
        "formula_sql": "COUNT(DISTINCT session_id)",
        "base_table": FACT_EVENTS,
        "default_time_column": "event_date",
        "aggregation_type": "count_distinct",
        "unit": "sessions",
        "example_question": "Có bao nhiêu phiên truy cập?",
    },
    {
        "metric_name": "unique_products",
        "business_name": "Unique products",
        "description": "Distinct products with events.",
        "formula_sql": "COUNT(DISTINCT product_id)",
        "base_table": FACT_EVENTS,
        "default_time_column": "event_date",
        "aggregation_type": "count_distinct",
        "unit": "products",
        "example_question": "Có bao nhiêu sản phẩm được tương tác?",
    },
    {
        "metric_name": "avg_event_price",
        "business_name": "Average event price",
        "description": "Average observed event price.",
        "formula_sql": "AVG(price)",
        "base_table": FACT_EVENTS,
        "default_time_column": "event_date",
        "aggregation_type": "avg",
        "unit": "currency",
        "example_question": "Giá trung bình của sự kiện là bao nhiêu?",
    },
]

JOIN_DEFINITIONS = [
    {
        "left_table": FACT_EVENTS,
        "left_key": "time_id",
        "right_table": DIM_TIME,
        "right_key": "time_id",
        "relationship_type": "many_to_one",
        "description": "Attach hourly time attributes to event facts.",
    },
    {
        "left_table": FACT_EVENTS,
        "left_key": "product_id",
        "right_table": DIM_PRODUCT,
        "right_key": "product_id",
        "relationship_type": "many_to_one",
        "description": "Attach product attributes to event facts.",
    },
    {
        "left_table": FACT_EVENTS,
        "left_key": "user_id",
        "right_table": DIM_USER,
        "right_key": "user_id",
        "relationship_type": "many_to_one",
        "description": "Attach user attributes to event facts.",
    },
    {
        "left_table": FACT_EVENTS,
        "left_key": "session_id",
        "right_table": DIM_SESSION,
        "right_key": "session_id",
        "relationship_type": "many_to_one",
        "description": "Attach session attributes to event facts.",
    },
    {
        "left_table": FACT_SALES,
        "left_key": "event_fingerprint",
        "right_table": FACT_EVENTS,
        "right_key": "event_fingerprint",
        "relationship_type": "one_to_one",
        "description": "Link a sale row back to its purchase event.",
    },
    {
        "left_table": FACT_SALES,
        "left_key": "time_id",
        "right_table": DIM_TIME,
        "right_key": "time_id",
        "relationship_type": "many_to_one",
        "description": "Attach hourly time attributes to sales.",
    },
    {
        "left_table": FACT_SALES,
        "left_key": "product_id",
        "right_table": DIM_PRODUCT,
        "right_key": "product_id",
        "relationship_type": "many_to_one",
        "description": "Attach product attributes to sales.",
    },
    {
        "left_table": FACT_SALES,
        "left_key": "user_id",
        "right_table": DIM_USER,
        "right_key": "user_id",
        "relationship_type": "many_to_one",
        "description": "Attach user attributes to sales.",
    },
    {
        "left_table": FACT_SALES,
        "left_key": "session_id",
        "right_table": DIM_SESSION,
        "right_key": "session_id",
        "relationship_type": "many_to_one",
        "description": "Attach session attributes to sales.",
    },
    {
        "left_table": DAILY_PRODUCT_SUMMARY,
        "left_key": "product_id",
        "right_table": DIM_PRODUCT,
        "right_key": "product_id",
        "relationship_type": "many_to_one",
        "description": "Attach current product attributes to product summaries.",
    },
]

