"""Human-readable Gold semantics for Text-to-SQL prompts.

These definitions intentionally describe only business-facing Gold tables and
columns. They do not model lineage, ranking, embeddings, or physical storage.
"""

from gold.config import (
    DAILY_BRAND_SUMMARY,
    DAILY_CATEGORY_SUMMARY,
    DAILY_EVENT_SUMMARY,
    DAILY_PRODUCT_SUMMARY,
    DIM_PRODUCT,
    DIM_SESSION,
    DIM_TIME,
    DIM_USER,
    FACT_EVENTS,
    FACT_SALES,
)


TABLE_DEFINITIONS = [
    {
        "table": DAILY_EVENT_SUMMARY,
        "display_name": "Daily event summary",
        "purpose": "Daily overall ecommerce traffic, conversion, and revenue metrics.",
        "grain": "1 row = 1 event_date.",
        "use_for": "Use for overall daily totals: events, views, carts, purchases, users, sessions, products, revenue, and conversion rates.",
        "query_notes": "Has event_date; for simple month/year filters, filter event_date directly and do not join dim_time. Not suitable for brand, product, or category breakdowns.",
        "is_agent_visible": True,
    },
    {
        "table": DAILY_PRODUCT_SUMMARY,
        "display_name": "Daily product summary",
        "purpose": "Daily product-level performance with product, brand, category, behavior, price, revenue, and conversion metrics.",
        "grain": "1 row = 1 event_date + 1 product_id.",
        "use_for": "Use for questions by product, brand, or category when product-level daily metrics are needed.",
        "query_notes": "Has event_date; for simple month/year filters, filter event_date directly and do not join dim_time. Good default for product, brand, and category performance questions.",
        "is_agent_visible": True,
    },
    {
        "table": DAILY_CATEGORY_SUMMARY,
        "display_name": "Daily category summary",
        "purpose": "Daily behavior, revenue, and conversion metrics by category hierarchy.",
        "grain": "1 row = 1 event_date + category_l1 + category_l2 + category_l3.",
        "use_for": "Use for category-level questions such as revenue, purchases, views, carts, users, products, and conversion by category.",
        "query_notes": "Has event_date; for simple month/year filters, filter event_date directly and do not join dim_time. Do not use for brand questions because this table has no brand column.",
        "is_agent_visible": True,
    },
    {
        "table": DAILY_BRAND_SUMMARY,
        "display_name": "Daily brand summary",
        "purpose": "Daily behavior, revenue, and conversion metrics by brand.",
        "grain": "1 row = 1 event_date + 1 brand.",
        "use_for": "Use for brand-level questions such as revenue, purchases, views, carts, users, products, and conversion by brand.",
        "query_notes": "Has event_date; for simple month/year filters, filter event_date directly and do not join dim_time. Do not use for category or product-specific questions because this table has no category or product_id columns.",
        "is_agent_visible": True,
    },
    {
        "table": FACT_EVENTS,
        "display_name": "Event fact",
        "purpose": "Detailed ecommerce behavior events with product, user, session, time, price, event type, and event-type flags.",
        "grain": "1 row = 1 unique ecommerce event.",
        "use_for": "Use only when summary tables cannot answer the question, for example raw event filtering, custom distinct counts, or detailed event conditions.",
        "query_notes": "Prefer daily summary tables for aggregate daily metrics. Use event_date for date filters. Join dim_product on product_id for current product attributes if needed.",
        "is_agent_visible": True,
    },
    {
        "table": FACT_SALES,
        "display_name": "Sales fact",
        "purpose": "Purchase events represented as sales rows with quantity and gross amount.",
        "grain": "1 row = 1 purchase event.",
        "use_for": "Use for detailed purchase, transaction, unit price, quantity, or gross amount questions when summary tables are not enough.",
        "query_notes": "Use sale_date for purchase date filters. For daily revenue totals, prefer daily_event_summary or the relevant daily summary table.",
        "is_agent_visible": True,
    },
    {
        "table": DIM_TIME,
        "display_name": "Time dimension",
        "purpose": "Calendar attributes for event time such as year, month, day, hour, weekday, month name, quarter, and weekend flag.",
        "grain": "1 row = 1 time_id hour.",
        "use_for": "Use when the question needs calendar attributes that are not already easy to derive from event_date, such as weekend or day name.",
        "query_notes": "Summary tables already have event_date; do not join dim_time for simple month/year filtering. Join facts on time_id only when time attributes are needed.",
        "is_agent_visible": True,
    },
    {
        "table": DIM_PRODUCT,
        "display_name": "Product dimension",
        "purpose": "Current product attributes and observed price range by product.",
        "grain": "1 row = 1 product_id.",
        "use_for": "Use for product lookup, brand/category attributes, and observed product price ranges.",
        "query_notes": "Join facts or product summaries on product_id when product attributes are missing from the base table.",
        "is_agent_visible": True,
    },
    {
        "table": DIM_USER,
        "display_name": "User dimension",
        "purpose": "User-level lifetime activity and purchase summary.",
        "grain": "1 row = 1 user_id.",
        "use_for": "Use for user-level behavior totals, first/last activity, total sessions, events, purchases, and revenue.",
        "query_notes": "This is a user summary table, not a daily table. Use fact_events or summary tables when date-level behavior is required.",
        "is_agent_visible": True,
    },
    {
        "table": DIM_SESSION,
        "display_name": "Session dimension",
        "purpose": "Session-level behavior, duration, revenue, and purchase flag.",
        "grain": "1 row = 1 session_id.",
        "use_for": "Use for session-level questions such as duration, events per session, revenue per session, and sessions with purchases.",
        "query_notes": "This is a session summary table, not a daily table. Use session_start_at or session_end_at for time filtering.",
        "is_agent_visible": True,
    },
]


AGENT_VISIBLE_COLUMNS = {
    DAILY_EVENT_SUMMARY: [
        "event_date",
        "total_events",
        "total_views",
        "total_carts",
        "total_remove_from_carts",
        "total_purchases",
        "unique_users",
        "unique_sessions",
        "unique_products",
        "unique_events",
        "total_revenue",
        "avg_event_price",
        "conversion_rate",
        "cart_to_purchase_rate",
    ],
    DAILY_PRODUCT_SUMMARY: [
        "event_date",
        "product_id",
        "brand",
        "category_l1",
        "category_l2",
        "category_l3",
        "view_count",
        "cart_count",
        "purchase_count",
        "remove_from_cart_count",
        "unique_events",
        "unique_users",
        "unique_sessions",
        "revenue",
        "avg_price",
        "min_price",
        "max_price",
        "conversion_rate",
        "cart_to_purchase_rate",
    ],
    DAILY_CATEGORY_SUMMARY: [
        "event_date",
        "category_l1",
        "category_l2",
        "category_l3",
        "total_events",
        "view_count",
        "cart_count",
        "purchase_count",
        "remove_from_cart_count",
        "unique_events",
        "unique_users",
        "unique_products",
        "revenue",
        "conversion_rate",
        "cart_to_purchase_rate",
    ],
    DAILY_BRAND_SUMMARY: [
        "event_date",
        "brand",
        "view_count",
        "cart_count",
        "purchase_count",
        "remove_from_cart_count",
        "unique_events",
        "unique_users",
        "unique_products",
        "revenue",
        "conversion_rate",
        "cart_to_purchase_rate",
    ],
    FACT_EVENTS: [
        "time_id",
        "event_ts",
        "event_date",
        "event_type",
        "product_id",
        "user_id",
        "session_id",
        "price",
        "is_view",
        "is_cart",
        "is_remove_from_cart",
        "is_purchase",
    ],
    FACT_SALES: [
        "time_id",
        "sale_ts",
        "sale_date",
        "product_id",
        "user_id",
        "session_id",
        "unit_price",
        "quantity",
        "gross_amount",
    ],
    DIM_TIME: [
        "time_id",
        "event_date",
        "event_year",
        "event_month",
        "event_day",
        "event_hour",
        "day_of_week",
        "day_name",
        "month_name",
        "quarter",
        "is_weekend",
    ],
    DIM_PRODUCT: [
        "product_id",
        "category_id",
        "category_code",
        "category_l1",
        "category_l2",
        "category_l3",
        "brand",
        "first_seen_at",
        "last_seen_at",
        "avg_observed_price",
        "min_observed_price",
        "max_observed_price",
        "record_count",
    ],
    DIM_USER: [
        "user_id",
        "first_seen_at",
        "last_seen_at",
        "total_sessions",
        "total_events",
        "total_views",
        "total_cart_adds",
        "total_remove_from_carts",
        "total_purchases",
        "total_revenue",
    ],
    DIM_SESSION: [
        "session_id",
        "user_id",
        "session_start_at",
        "session_end_at",
        "session_duration_sec",
        "event_count",
        "view_count",
        "cart_count",
        "remove_from_cart_count",
        "purchase_count",
        "session_revenue",
        "has_purchase",
    ],
}


COMMON_COLUMN_DEFINITIONS = {
    "time_id": {
        "meaning": "Hourly time key in yyyyMMddHH format.",
        "business_terms": "time id, khóa thời gian, khoa thoi gian, giờ, gio, hour",
        "example_usage": "JOIN gold.dim_time USING (time_id)",
    },
    "event_ts": {
        "meaning": "Timestamp when the event happened.",
        "business_terms": "thời điểm sự kiện, thoi diem su kien, event time, timestamp",
        "example_usage": "WHERE event_ts >= TIMESTAMP '2025-01-01 00:00:00'",
    },
    "sale_ts": {
        "meaning": "Timestamp when the purchase happened.",
        "business_terms": "thời điểm mua, thoi diem mua, sale time, purchase time, timestamp",
        "example_usage": "WHERE sale_ts >= TIMESTAMP '2025-01-01 00:00:00'",
    },
    "event_date": {
        "meaning": "Calendar date of the event or daily summary.",
        "business_terms": "ngày, ngay, tháng, thang, năm, nam, date, daily",
        "example_usage": "WHERE event_date BETWEEN DATE '2025-01-01' AND DATE '2025-01-31'",
    },
    "sale_date": {
        "meaning": "Calendar date of the purchase event.",
        "business_terms": "ngày mua, ngay mua, ngày bán, ngay ban, sale date, purchase date",
        "example_usage": "WHERE sale_date BETWEEN DATE '2025-01-01' AND DATE '2025-01-31'",
    },
    "event_year": {
        "meaning": "Year number of the event.",
        "business_terms": "năm, nam, year",
        "example_usage": "WHERE event_year = 2025",
    },
    "event_month": {
        "meaning": "Month number of the event from 1 to 12.",
        "business_terms": "tháng, thang, month",
        "example_usage": "WHERE event_month = 1",
    },
    "event_day": {
        "meaning": "Day of month of the event.",
        "business_terms": "ngày trong tháng, ngay trong thang, day",
        "example_usage": "WHERE event_day = 15",
    },
    "event_hour": {
        "meaning": "Hour of day of the event from 0 to 23.",
        "business_terms": "giờ, gio, hour",
        "example_usage": "GROUP BY event_hour",
    },
    "day_of_week": {
        "meaning": "Day-of-week number from Spark dayofweek.",
        "business_terms": "thứ, thu, ngày trong tuần, ngay trong tuan, weekday",
        "example_usage": "GROUP BY day_of_week",
    },
    "day_name": {
        "meaning": "Day-of-week name.",
        "business_terms": "thứ, thu, tên ngày, ten ngay, day name, weekday name",
        "example_usage": "GROUP BY day_name",
    },
    "month_name": {
        "meaning": "Month name.",
        "business_terms": "tên tháng, ten thang, month name",
        "example_usage": "GROUP BY month_name",
    },
    "quarter": {
        "meaning": "Calendar quarter from 1 to 4.",
        "business_terms": "quý, quy, quarter",
        "example_usage": "GROUP BY quarter",
    },
    "is_weekend": {
        "meaning": "True when the event date is Saturday or Sunday.",
        "business_terms": "cuối tuần, cuoi tuan, weekend",
        "example_usage": "WHERE is_weekend = true",
    },
    "event_type": {
        "meaning": "User behavior type for the event: view, cart, remove_from_cart, or purchase.",
        "business_terms": "loại sự kiện, loai su kien, hành vi, hanh vi, event type",
        "example_usage": "WHERE event_type = 'purchase'",
    },
    "product_id": {
        "meaning": "Product identifier.",
        "business_terms": "sản phẩm, san pham, mã sản phẩm, ma san pham, product, product id",
        "example_usage": "GROUP BY product_id",
    },
    "category_id": {
        "meaning": "Source category identifier.",
        "business_terms": "mã danh mục, ma danh muc, category id",
        "example_usage": "WHERE category_id IS NOT NULL",
    },
    "category_code": {
        "meaning": "Source category code string.",
        "business_terms": "mã ngành hàng, ma nganh hang, mã danh mục, category code",
        "example_usage": "GROUP BY category_code",
    },
    "category_l1": {
        "meaning": "Top-level product category.",
        "business_terms": "danh mục, danh muc, ngành hàng, nganh hang, category, category l1",
        "example_usage": "GROUP BY category_l1",
    },
    "category_l2": {
        "meaning": "Second-level product category.",
        "business_terms": "danh mục cấp 2, danh muc cap 2, ngành hàng cấp 2, category l2",
        "example_usage": "GROUP BY category_l2",
    },
    "category_l3": {
        "meaning": "Third-level product category.",
        "business_terms": "danh mục cấp 3, danh muc cap 3, ngành hàng cấp 3, category l3",
        "example_usage": "GROUP BY category_l3",
    },
    "brand": {
        "meaning": "Product brand.",
        "business_terms": "brand, nhãn hàng, nhan hang, thương hiệu, thuong hieu, hãng, hang",
        "example_usage": "GROUP BY brand",
    },
    "user_id": {
        "meaning": "User identifier.",
        "business_terms": "người dùng, nguoi dung, khách hàng, khach hang, user, customer",
        "example_usage": "COUNT(DISTINCT user_id)",
    },
    "session_id": {
        "meaning": "User session identifier.",
        "business_terms": "phiên, phien, phiên truy cập, phien truy cap, session",
        "example_usage": "COUNT(DISTINCT session_id)",
    },
    "price": {
        "meaning": "Observed product price on an event.",
        "business_terms": "giá, gia, giá sản phẩm, gia san pham, price",
        "example_usage": "AVG(price) AS avg_price",
    },
    "unit_price": {
        "meaning": "Unit price for a purchase event.",
        "business_terms": "đơn giá, don gia, giá bán, gia ban, unit price",
        "example_usage": "AVG(unit_price) AS avg_unit_price",
    },
    "quantity": {
        "meaning": "Purchase quantity; current event data uses quantity 1 per purchase event.",
        "business_terms": "số lượng, so luong, quantity, units",
        "example_usage": "SUM(quantity) AS units_sold",
    },
    "gross_amount": {
        "meaning": "Purchase revenue amount before adjustments.",
        "business_terms": "doanh thu, revenue, sales, tổng tiền, tong tien, gross amount",
        "example_usage": "SUM(gross_amount) AS revenue",
    },
    "revenue": {
        "meaning": "Revenue at the table grain.",
        "business_terms": "doanh thu, revenue, sales, tổng tiền, tong tien",
        "example_usage": "SUM(revenue) AS total_revenue",
    },
    "total_revenue": {
        "meaning": "Total revenue at the table grain.",
        "business_terms": "doanh thu, revenue, sales, tổng tiền, tong tien",
        "example_usage": "SUM(total_revenue) AS total_revenue",
    },
    "session_revenue": {
        "meaning": "Revenue generated in the session.",
        "business_terms": "doanh thu phiên, doanh thu phien, session revenue",
        "example_usage": "SUM(session_revenue) AS total_session_revenue",
    },
    "view_count": {
        "meaning": "Number of view events at the table grain.",
        "business_terms": "lượt xem, luot xem, xem, viewed, views",
        "example_usage": "SUM(view_count) AS views",
    },
    "total_views": {
        "meaning": "Total number of view events at the table grain.",
        "business_terms": "lượt xem, luot xem, xem, viewed, views",
        "example_usage": "SUM(total_views) AS views",
    },
    "cart_count": {
        "meaning": "Number of add-to-cart events at the table grain.",
        "business_terms": "giỏ hàng, gio hang, thêm vào giỏ, them vao gio, add to cart",
        "example_usage": "SUM(cart_count) AS carts",
    },
    "total_carts": {
        "meaning": "Total number of add-to-cart events at the table grain.",
        "business_terms": "giỏ hàng, gio hang, thêm vào giỏ, them vao gio, add to cart",
        "example_usage": "SUM(total_carts) AS carts",
    },
    "total_cart_adds": {
        "meaning": "Total add-to-cart events for the user.",
        "business_terms": "giỏ hàng, gio hang, thêm vào giỏ, them vao gio, add to cart",
        "example_usage": "SUM(total_cart_adds) AS total_cart_adds",
    },
    "purchase_count": {
        "meaning": "Number of purchase events at the table grain.",
        "business_terms": "lượt mua, luot mua, mua hàng, mua hang, purchase, purchases",
        "example_usage": "SUM(purchase_count) AS purchases",
    },
    "total_purchases": {
        "meaning": "Total number of purchase events at the table grain.",
        "business_terms": "lượt mua, luot mua, mua hàng, mua hang, purchase, purchases",
        "example_usage": "SUM(total_purchases) AS purchases",
    },
    "remove_from_cart_count": {
        "meaning": "Number of remove-from-cart events at the table grain.",
        "business_terms": "bỏ giỏ, bo gio, xóa khỏi giỏ, xoa khoi gio, remove from cart",
        "example_usage": "SUM(remove_from_cart_count) AS remove_from_carts",
    },
    "total_remove_from_carts": {
        "meaning": "Total number of remove-from-cart events at the table grain.",
        "business_terms": "bỏ giỏ, bo gio, xóa khỏi giỏ, xoa khoi gio, remove from cart",
        "example_usage": "SUM(total_remove_from_carts) AS remove_from_carts",
    },
    "total_events": {
        "meaning": "Total number of ecommerce events at the table grain.",
        "business_terms": "sự kiện, su kien, lượt sự kiện, luot su kien, events",
        "example_usage": "SUM(total_events) AS total_events",
    },
    "event_count": {
        "meaning": "Number of events in the session.",
        "business_terms": "sự kiện, su kien, lượt sự kiện, luot su kien, events",
        "example_usage": "AVG(event_count) AS avg_events_per_session",
    },
    "unique_events": {
        "meaning": "Distinct event count at the table grain.",
        "business_terms": "sự kiện duy nhất, su kien duy nhat, unique events",
        "example_usage": "SUM(unique_events) AS unique_events",
    },
    "unique_users": {
        "meaning": "Distinct user count at the table grain.",
        "business_terms": "người dùng, nguoi dung, khách hàng, khach hang, unique users",
        "example_usage": "SUM(unique_users) AS unique_users",
    },
    "unique_sessions": {
        "meaning": "Distinct session count at the table grain.",
        "business_terms": "phiên, phien, phiên truy cập, phien truy cap, unique sessions",
        "example_usage": "SUM(unique_sessions) AS unique_sessions",
    },
    "unique_products": {
        "meaning": "Distinct product count at the table grain.",
        "business_terms": "sản phẩm, san pham, số sản phẩm, so san pham, unique products",
        "example_usage": "SUM(unique_products) AS unique_products",
    },
    "avg_event_price": {
        "meaning": "Average observed price across events at the table grain.",
        "business_terms": "giá trung bình, gia trung binh, average price, avg price",
        "example_usage": "AVG(avg_event_price) AS avg_event_price",
    },
    "avg_price": {
        "meaning": "Average observed price at the table grain.",
        "business_terms": "giá trung bình, gia trung binh, average price, avg price",
        "example_usage": "AVG(avg_price) AS avg_price",
    },
    "min_price": {
        "meaning": "Minimum observed price at the table grain.",
        "business_terms": "giá thấp nhất, gia thap nhat, minimum price, min price",
        "example_usage": "MIN(min_price) AS min_price",
    },
    "max_price": {
        "meaning": "Maximum observed price at the table grain.",
        "business_terms": "giá cao nhất, gia cao nhat, maximum price, max price",
        "example_usage": "MAX(max_price) AS max_price",
    },
    "conversion_rate": {
        "meaning": "Purchases divided by views at the table grain.",
        "business_terms": "tỷ lệ chuyển đổi, ty le chuyen doi, conversion rate, CR",
        "example_usage": "AVG(conversion_rate) AS avg_conversion_rate",
    },
    "cart_to_purchase_rate": {
        "meaning": "Purchases divided by add-to-cart events at the table grain.",
        "business_terms": "tỷ lệ giỏ sang mua, ty le gio sang mua, cart to purchase rate",
        "example_usage": "AVG(cart_to_purchase_rate) AS avg_cart_to_purchase_rate",
    },
    "first_seen_at": {
        "meaning": "First timestamp observed for the entity.",
        "business_terms": "lần đầu thấy, lan dau thay, first seen, first activity",
        "example_usage": "MIN(first_seen_at) AS first_seen_at",
    },
    "last_seen_at": {
        "meaning": "Last timestamp observed for the entity.",
        "business_terms": "lần cuối thấy, lan cuoi thay, last seen, last activity",
        "example_usage": "MAX(last_seen_at) AS last_seen_at",
    },
    "avg_observed_price": {
        "meaning": "Average observed product price.",
        "business_terms": "giá trung bình, gia trung binh, average observed price",
        "example_usage": "ORDER BY avg_observed_price DESC",
    },
    "min_observed_price": {
        "meaning": "Minimum observed product price.",
        "business_terms": "giá thấp nhất, gia thap nhat, minimum observed price",
        "example_usage": "ORDER BY min_observed_price ASC",
    },
    "max_observed_price": {
        "meaning": "Maximum observed product price.",
        "business_terms": "giá cao nhất, gia cao nhat, maximum observed price",
        "example_usage": "ORDER BY max_observed_price DESC",
    },
    "record_count": {
        "meaning": "Number of source observations behind the product dimension row.",
        "business_terms": "số bản ghi, so ban ghi, record count, observations",
        "example_usage": "ORDER BY record_count DESC",
    },
    "total_sessions": {
        "meaning": "Total sessions for the user.",
        "business_terms": "số phiên, so phien, phiên truy cập, sessions",
        "example_usage": "ORDER BY total_sessions DESC",
    },
    "session_start_at": {
        "meaning": "First event timestamp in the session.",
        "business_terms": "bắt đầu phiên, bat dau phien, session start",
        "example_usage": "WHERE session_start_at >= TIMESTAMP '2025-01-01 00:00:00'",
    },
    "session_end_at": {
        "meaning": "Last event timestamp in the session.",
        "business_terms": "kết thúc phiên, ket thuc phien, session end",
        "example_usage": "WHERE session_end_at < TIMESTAMP '2025-02-01 00:00:00'",
    },
    "session_duration_sec": {
        "meaning": "Session duration in seconds.",
        "business_terms": "thời lượng phiên, thoi luong phien, session duration",
        "example_usage": "AVG(session_duration_sec) AS avg_session_duration_sec",
    },
    "has_purchase": {
        "meaning": "True when the session contains at least one purchase.",
        "business_terms": "có mua, co mua, mua hàng, purchased session",
        "example_usage": "WHERE has_purchase = true",
    },
    "is_view": {
        "meaning": "True when the event_type is view.",
        "business_terms": "lượt xem, luot xem, view flag, is view",
        "example_usage": "WHERE is_view = true",
    },
    "is_cart": {
        "meaning": "True when the event_type is cart.",
        "business_terms": "giỏ hàng, gio hang, add to cart flag, is cart",
        "example_usage": "WHERE is_cart = true",
    },
    "is_remove_from_cart": {
        "meaning": "True when the event_type is remove_from_cart.",
        "business_terms": "bỏ giỏ, bo gio, remove from cart flag",
        "example_usage": "WHERE is_remove_from_cart = true",
    },
    "is_purchase": {
        "meaning": "True when the event_type is purchase.",
        "business_terms": "lượt mua, luot mua, purchase flag, is purchase",
        "example_usage": "WHERE is_purchase = true",
    },
}


TABLE_COLUMN_OVERRIDES = {}
