"""Gold and metadata table definitions."""


MVP_TABLE_NAMES = [
    "dim_time",
    "dim_product",
    "fact_events",
    "fact_sales",
    "daily_event_summary",
]

EXTENDED_TABLE_NAMES = [
    "dim_user",
    "dim_session",
    "daily_product_summary",
    "daily_category_summary",
    "daily_brand_summary",
]

GOLD_TABLE_NAMES = MVP_TABLE_NAMES + EXTENDED_TABLE_NAMES

METADATA_TABLE_NAMES = [
    "table_catalog",
    "column_catalog",
    "metric_catalog",
    "join_catalog",
]


def properties(table_type, grain, primary_key, source, comment, recommended="true"):
    return {
        "format-version": "2",
        "write.parquet.compression-codec": "snappy",
        "gold.layer": "gold",
        "gold.table_type": table_type,
        "gold.grain": grain,
        "gold.primary_key": primary_key,
        "gold.source": source,
        "agent.visible": "true",
        "agent.recommended": recommended,
        "comment": comment,
    }


GOLD_TABLES = [
    {
        "name": "dim_time",
        "namespace": "gold",
        "columns": [
            ("time_id", "STRING"),
            ("event_date", "DATE"),
            ("event_year", "INT"),
            ("event_month", "INT"),
            ("event_day", "INT"),
            ("event_hour", "INT"),
            ("day_of_week", "INT"),
            ("day_name", "STRING"),
            ("month_name", "STRING"),
            ("quarter", "INT"),
            ("is_weekend", "BOOLEAN"),
            ("created_at", "TIMESTAMP"),
            ("updated_at", "TIMESTAMP"),
        ],
        "partition": "event_year, event_month",
        "properties": properties(
            "dimension",
            "one row per event hour",
            "time_id",
            "silver.ecommerce_events",
            "Time dimension for hourly and daily ecommerce analytics",
        ),
    },
    {
        "name": "dim_product",
        "namespace": "gold",
        "columns": [
            ("product_id", "BIGINT"),
            ("category_id", "BIGINT"),
            ("category_code", "STRING"),
            ("category_l1", "STRING"),
            ("category_l2", "STRING"),
            ("category_l3", "STRING"),
            ("brand", "STRING"),
            ("first_seen_at", "TIMESTAMP"),
            ("last_seen_at", "TIMESTAMP"),
            ("avg_observed_price", "DECIMAL(10,2)"),
            ("min_observed_price", "DECIMAL(10,2)"),
            ("max_observed_price", "DECIMAL(10,2)"),
            ("record_count", "BIGINT"),
            ("created_at", "TIMESTAMP"),
            ("updated_at", "TIMESTAMP"),
        ],
        "properties": properties(
            "dimension",
            "one row per product",
            "product_id",
            "silver.ecommerce_events",
            "Product dimension with category hierarchy, brand, and observed price statistics",
        ),
    },
    {
        "name": "fact_events",
        "namespace": "gold",
        "columns": [
            ("event_id", "STRING"),
            ("source_event_id", "STRING"),
            ("time_id", "STRING"),
            ("event_ts", "TIMESTAMP"),
            ("event_date", "DATE"),
            ("event_type", "STRING"),
            ("product_id", "BIGINT"),
            ("user_id", "BIGINT"),
            ("session_id", "STRING"),
            ("price", "DECIMAL(10,2)"),
            ("is_view", "BOOLEAN"),
            ("is_cart", "BOOLEAN"),
            ("is_remove_from_cart", "BOOLEAN"),
            ("is_purchase", "BOOLEAN"),
            ("kafka_partition", "INT"),
            ("kafka_offset", "BIGINT"),
            ("silver_processed_at", "TIMESTAMP"),
            ("gold_processed_at", "TIMESTAMP"),
        ],
        "partition": "days(event_ts)",
        "properties": properties(
            "fact",
            "one row per clean ecommerce event",
            "event_id",
            "silver.ecommerce_events",
            "Central event fact table derived from clean Silver ecommerce events",
        ),
    },
    {
        "name": "fact_sales",
        "namespace": "gold",
        "columns": [
            ("sale_id", "STRING"),
            ("source_event_id", "STRING"),
            ("time_id", "STRING"),
            ("sale_ts", "TIMESTAMP"),
            ("sale_date", "DATE"),
            ("product_id", "BIGINT"),
            ("user_id", "BIGINT"),
            ("session_id", "STRING"),
            ("unit_price", "DECIMAL(10,2)"),
            ("quantity", "INT"),
            ("gross_amount", "DECIMAL(18,2)"),
            ("gold_processed_at", "TIMESTAMP"),
        ],
        "partition": "days(sale_ts)",
        "properties": properties(
            "fact",
            "one row per purchase event",
            "sale_id",
            "silver.ecommerce_events where event_type = purchase",
            "Sales fact table containing purchase events. quantity defaults to 1 because source dataset has no quantity column",
        ),
    },
    {
        "name": "daily_event_summary",
        "namespace": "gold",
        "columns": [
            ("event_date", "DATE"),
            ("total_events", "BIGINT"),
            ("total_views", "BIGINT"),
            ("total_carts", "BIGINT"),
            ("total_remove_from_carts", "BIGINT"),
            ("total_purchases", "BIGINT"),
            ("unique_users", "BIGINT"),
            ("unique_sessions", "BIGINT"),
            ("unique_products", "BIGINT"),
            ("total_revenue", "DECIMAL(18,2)"),
            ("avg_event_price", "DECIMAL(10,2)"),
            ("conversion_rate", "DOUBLE"),
            ("cart_to_purchase_rate", "DOUBLE"),
            ("gold_processed_at", "TIMESTAMP"),
        ],
        "partition": "event_date",
        "properties": properties(
            "summary",
            "one row per event date",
            "event_date",
            "silver.ecommerce_events aggregated by event_date",
            "Daily ecommerce event summary for fast analytics and AI Agent queries",
        ),
    },
    {
        "name": "dim_user",
        "namespace": "gold",
        "columns": [
            ("user_id", "BIGINT"),
            ("first_seen_at", "TIMESTAMP"),
            ("last_seen_at", "TIMESTAMP"),
            ("total_sessions", "BIGINT"),
            ("total_events", "BIGINT"),
            ("total_views", "BIGINT"),
            ("total_cart_adds", "BIGINT"),
            ("total_remove_from_carts", "BIGINT"),
            ("total_purchases", "BIGINT"),
            ("total_revenue", "DECIMAL(18,2)"),
            ("created_at", "TIMESTAMP"),
            ("updated_at", "TIMESTAMP"),
        ],
        "properties": properties(
            "dimension",
            "one row per user",
            "user_id",
            "gold.fact_events and gold.fact_sales",
            "User behavior dimension aggregated from clean ecommerce events",
            recommended="false",
        ),
    },
    {
        "name": "dim_session",
        "namespace": "gold",
        "columns": [
            ("session_id", "STRING"),
            ("user_id", "BIGINT"),
            ("session_start_at", "TIMESTAMP"),
            ("session_end_at", "TIMESTAMP"),
            ("session_duration_sec", "BIGINT"),
            ("event_count", "BIGINT"),
            ("view_count", "BIGINT"),
            ("cart_count", "BIGINT"),
            ("remove_from_cart_count", "BIGINT"),
            ("purchase_count", "BIGINT"),
            ("session_revenue", "DECIMAL(18,2)"),
            ("has_purchase", "BOOLEAN"),
            ("created_at", "TIMESTAMP"),
            ("updated_at", "TIMESTAMP"),
        ],
        "partition": "days(session_start_at)",
        "properties": properties(
            "dimension",
            "one row per user session",
            "session_id",
            "gold.fact_events and gold.fact_sales",
            "Session dimension with behavior counts, duration, and revenue",
            recommended="false",
        ),
    },
    {
        "name": "daily_product_summary",
        "namespace": "gold",
        "columns": [
            ("summary_id", "STRING"),
            ("event_date", "DATE"),
            ("product_id", "BIGINT"),
            ("brand", "STRING"),
            ("category_l1", "STRING"),
            ("category_l2", "STRING"),
            ("category_l3", "STRING"),
            ("view_count", "BIGINT"),
            ("cart_count", "BIGINT"),
            ("purchase_count", "BIGINT"),
            ("remove_from_cart_count", "BIGINT"),
            ("unique_users", "BIGINT"),
            ("unique_sessions", "BIGINT"),
            ("revenue", "DECIMAL(18,2)"),
            ("avg_price", "DECIMAL(10,2)"),
            ("min_price", "DECIMAL(10,2)"),
            ("max_price", "DECIMAL(10,2)"),
            ("conversion_rate", "DOUBLE"),
            ("cart_to_purchase_rate", "DOUBLE"),
            ("gold_processed_at", "TIMESTAMP"),
        ],
        "partition": "event_date",
        "properties": properties(
            "summary",
            "one row per event date and product",
            "summary_id",
            "gold.fact_events joined with gold.dim_product",
            "Daily product performance summary for analytics and AI Agent queries",
        ),
    },
    {
        "name": "daily_category_summary",
        "namespace": "gold",
        "columns": [
            ("summary_id", "STRING"),
            ("event_date", "DATE"),
            ("category_l1", "STRING"),
            ("category_l2", "STRING"),
            ("category_l3", "STRING"),
            ("total_events", "BIGINT"),
            ("view_count", "BIGINT"),
            ("cart_count", "BIGINT"),
            ("purchase_count", "BIGINT"),
            ("remove_from_cart_count", "BIGINT"),
            ("unique_users", "BIGINT"),
            ("unique_sessions", "BIGINT"),
            ("unique_products", "BIGINT"),
            ("revenue", "DECIMAL(18,2)"),
            ("conversion_rate", "DOUBLE"),
            ("cart_to_purchase_rate", "DOUBLE"),
            ("gold_processed_at", "TIMESTAMP"),
        ],
        "partition": "event_date",
        "properties": properties(
            "summary",
            "one row per event date and category hierarchy",
            "summary_id",
            "gold.fact_events joined with gold.dim_product",
            "Daily category-level ecommerce performance summary",
        ),
    },
    {
        "name": "daily_brand_summary",
        "namespace": "gold",
        "columns": [
            ("summary_id", "STRING"),
            ("event_date", "DATE"),
            ("brand", "STRING"),
            ("view_count", "BIGINT"),
            ("cart_count", "BIGINT"),
            ("purchase_count", "BIGINT"),
            ("remove_from_cart_count", "BIGINT"),
            ("unique_users", "BIGINT"),
            ("unique_sessions", "BIGINT"),
            ("unique_products", "BIGINT"),
            ("revenue", "DECIMAL(18,2)"),
            ("conversion_rate", "DOUBLE"),
            ("cart_to_purchase_rate", "DOUBLE"),
            ("gold_processed_at", "TIMESTAMP"),
        ],
        "partition": "event_date",
        "properties": properties(
            "summary",
            "one row per event date and brand",
            "summary_id",
            "gold.fact_events joined with gold.dim_product",
            "Daily brand-level ecommerce performance summary",
        ),
    },
]


METADATA_TABLES = [
    {
        "name": "table_catalog",
        "namespace": "metadata",
        "columns": [
            ("table_name", "STRING"),
            ("layer", "STRING"),
            ("table_type", "STRING"),
            ("business_name", "STRING"),
            ("description", "STRING"),
            ("grain", "STRING"),
            ("primary_key", "STRING"),
            ("storage_format", "STRING"),
            ("query_engine", "STRING"),
            ("is_agent_visible", "BOOLEAN"),
            ("recommended_for_agent", "BOOLEAN"),
            ("refresh_frequency", "STRING"),
            ("owner", "STRING"),
            ("created_at", "TIMESTAMP"),
            ("updated_at", "TIMESTAMP"),
        ],
        "properties": {
            "format-version": "2",
            "write.parquet.compression-codec": "snappy",
            "metadata.layer": "metadata",
            "agent.visible": "true",
            "comment": "Semantic table catalog for Agent4DA",
        },
    },
    {
        "name": "column_catalog",
        "namespace": "metadata",
        "columns": [
            ("column_id", "STRING"),
            ("table_name", "STRING"),
            ("column_name", "STRING"),
            ("data_type", "STRING"),
            ("business_name", "STRING"),
            ("description", "STRING"),
            ("source_table", "STRING"),
            ("source_column", "STRING"),
            ("transformation_logic", "STRING"),
            ("is_nullable", "BOOLEAN"),
            ("is_dimension", "BOOLEAN"),
            ("is_metric", "BOOLEAN"),
            ("is_time_column", "BOOLEAN"),
            ("is_join_key", "BOOLEAN"),
            ("example_values", "STRING"),
            ("allowed_values", "STRING"),
            ("agent_synonyms", "STRING"),
            ("created_at", "TIMESTAMP"),
            ("updated_at", "TIMESTAMP"),
        ],
        "properties": {
            "format-version": "2",
            "write.parquet.compression-codec": "snappy",
            "metadata.layer": "metadata",
            "agent.visible": "true",
            "comment": "Semantic column catalog for Agent4DA",
        },
    },
    {
        "name": "metric_catalog",
        "namespace": "metadata",
        "columns": [
            ("metric_name", "STRING"),
            ("business_name", "STRING"),
            ("description", "STRING"),
            ("formula_sql", "STRING"),
            ("base_table", "STRING"),
            ("default_time_column", "STRING"),
            ("aggregation_type", "STRING"),
            ("unit", "STRING"),
            ("example_question", "STRING"),
            ("created_at", "TIMESTAMP"),
            ("updated_at", "TIMESTAMP"),
        ],
        "properties": {
            "format-version": "2",
            "write.parquet.compression-codec": "snappy",
            "metadata.layer": "metadata",
            "agent.visible": "true",
            "comment": "Semantic metric catalog for Agent4DA",
        },
    },
    {
        "name": "join_catalog",
        "namespace": "metadata",
        "columns": [
            ("join_id", "STRING"),
            ("left_table", "STRING"),
            ("left_key", "STRING"),
            ("right_table", "STRING"),
            ("right_key", "STRING"),
            ("relationship_type", "STRING"),
            ("description", "STRING"),
            ("created_at", "TIMESTAMP"),
            ("updated_at", "TIMESTAMP"),
        ],
        "properties": {
            "format-version": "2",
            "write.parquet.compression-codec": "snappy",
            "metadata.layer": "metadata",
            "agent.visible": "true",
            "comment": "Semantic join catalog for Agent4DA",
        },
    },
]

