import { Lightbulb } from "lucide-react";
import type { AskKeyNumber } from "@/lib/types";

interface Props {
  summary: string | null;
  keyNumbers: AskKeyNumber[];
}

function formatValue(v: unknown): string {
  if (v === null || v === undefined) return "—";
  if (typeof v === "number") {
    if (Math.abs(v) >= 1000) return v.toLocaleString();
    return String(v);
  }
  return String(v);
}

export function AnswerPanel({ summary, keyNumbers }: Props) {
  if (!summary && (!keyNumbers || keyNumbers.length === 0)) {
    return (
      <p className="text-sm text-text-secondary">
        No summary yet. Run a question, or enable summarize in Settings.
      </p>
    );
  }

  return (
    <div className="space-y-4">
      {summary && (
        <div className="flex items-start gap-2 rounded-md border border-border bg-background p-3">
          <Lightbulb className="mt-0.5 h-4 w-4 text-warning" aria-hidden="true" />
          <p className="text-sm leading-relaxed text-text-primary">{summary}</p>
        </div>
      )}

      {keyNumbers && keyNumbers.length > 0 && (
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
          {keyNumbers.map((kn, i) => (
            <div
              key={i}
              className="rounded-md border border-border bg-surface p-3 shadow-card"
            >
              <p className="text-[11px] uppercase tracking-wide text-text-secondary">
                {kn.label}
              </p>
              <p className="mt-1 text-lg font-semibold text-text-primary">
                {formatValue(kn.value)}
              </p>
              {kn.delta && (
                <p className="text-[11px] text-text-secondary">{kn.delta}</p>
              )}
            </div>
          ))}
        </div>
      )}

      <p className="text-[11px] text-text-secondary">
        Summary generated by AI. Verify numbers against the Table tab.
      </p>
    </div>
  );
}
