"use client";

import { useMemo, useState } from "react";
import { BarChart3, FileCode, Lightbulb, ShieldCheck, Table2 } from "lucide-react";
import { ActionBar } from "./ActionBar";
import { AnswerPanel } from "./AnswerPanel";
import { ChartPanel } from "./ChartPanel";
import { SqlPanel } from "./SqlPanel";
import { TablePanel } from "./TablePanel";
import { api } from "@/lib/api";
import type { AskResult } from "@/lib/types";
import { cn } from "@/lib/utils";

type DetailTab = "table" | "sql" | "check";

interface Props {
  result: AskResult;
  onRetry: () => void;
  onClarify: (question: string) => void;
}

const DETAIL_TABS: Array<{ key: DetailTab; label: string; icon: typeof Table2 }> = [
  { key: "table", label: "Bảng dữ liệu", icon: Table2 },
  { key: "sql", label: "Xem truy vấn", icon: FileCode },
  { key: "check", label: "Kiểm chứng", icon: ShieldCheck },
];

function hasChart(result: AskResult): boolean {
  if (result.chart_suggestion) return true;
  return result.rows.length > 0 && result.columns.length >= 2;
}

export function ChatResultBlock({ result, onRetry, onClarify }: Props) {
  const [detailTab, setDetailTab] = useState<DetailTab | null>(null);
  const suggestions = result.clarification_suggestions ?? [];
  const assumptions = result.assumptions ?? [];
  const shouldClarify = suggestions.length > 0;
  const chartAvailable = hasChart(result);

  const verificationLines = useMemo(() => {
    const lines: string[] = [];
    if (result.guard_status) lines.push(`Bộ lọc an toàn: ${result.guard_status}`);
    if (result.intent) lines.push(`Intent: ${result.intent}`);
    lines.push(`Engine: ${result.agent_engine}`);
    if (result.latency_ms != null) lines.push(`Thời gian xử lý: ${result.latency_ms} ms`);
    lines.push(`Số dòng trả về: ${result.row_count.toLocaleString()}`);
    for (const note of result.validation_notes ?? []) lines.push(note);
    return lines;
  }, [result]);

  function handleSuggestion(question: string, index: number) {
    const selected = suggestions[index];
    if (selected) {
      void api.post("/agent/feedback", {
        json: {
          feedback_type: "suggestion_click",
          run_id: result.run_id,
          session_id: result.session_id,
          selected_suggestion: selected,
        },
      }).catch(() => {
        /* feedback is best-effort */
      });
    }
    onClarify(question);
  }

  return (
    <div className="space-y-3">
      {result.error && (
        <div
          role="alert"
          className="rounded-md border border-error/40 bg-error/10 p-3 text-sm text-error"
        >
          {result.error}
        </div>
      )}

      {/* 1. Short answer + main insight + KPIs first. */}
      <AnswerPanel summary={result.answer ?? result.summary} keyNumbers={result.key_numbers} />

      {assumptions.length > 0 && (
        <div className="rounded-md border border-warning/30 bg-warning/10 p-3">
          <p className="text-xs font-medium text-text-primary">Giả định đang dùng</p>
          <ul className="mt-1 list-disc space-y-1 pl-5 text-xs text-text-secondary">
            {assumptions.map((line, index) => (
              <li key={index}>{line}</li>
            ))}
          </ul>
        </div>
      )}

      {result.insights.length > 0 && (
        <div className="flex items-start gap-2 rounded-md border border-accent/30 bg-accent/5 p-3">
          <Lightbulb className="mt-0.5 h-4 w-4 shrink-0 text-accent" aria-hidden="true" />
          <ul className="space-y-1 text-sm text-text-primary">
            {result.insights.map((line, index) => (
              <li key={index}>{line}</li>
            ))}
          </ul>
        </div>
      )}

      {/* 2. Chart next (shown, not collapsed). */}
      {chartAvailable && (
        <section className="rounded-md border border-border bg-background p-3">
          <div className="mb-2 flex items-center gap-1.5 text-xs font-medium text-text-secondary">
            <BarChart3 className="h-4 w-4 text-accent" aria-hidden="true" />
            Biểu đồ
          </div>
          <ChartPanel
            columns={result.columns}
            rows={result.rows}
            suggestion={result.chart_suggestion}
          />
        </section>
      )}

      {/* Contextual clarification choices generated by the backend. */}
      {shouldClarify && (
        <section className="rounded-md border border-warning/40 bg-warning/10 p-3">
          <p className="text-sm font-medium text-text-primary">
            Gợi ý tiếp theo theo ngữ cảnh câu hỏi này:
          </p>
          <div className="mt-2 flex flex-wrap gap-2">
            {suggestions.map((choice, index) => (
              <button
                key={`${choice.question}-${index}`}
                type="button"
                title={choice.reason}
                onClick={() => handleSuggestion(choice.question, index)}
                className="rounded-md border border-warning/40 bg-surface px-3 py-1.5 text-xs text-text-primary hover:bg-warning/10"
              >
                {choice.label}
              </button>
            ))}
          </div>
        </section>
      )}

      {/* 3. Table / SQL / verification behind expandable tabs. */}
      <section className="rounded-md border border-border bg-background">
        <div className="flex flex-wrap items-center gap-1 border-b border-border p-2">
          {DETAIL_TABS.map(({ key, label, icon: Icon }) => (
            <button
              key={key}
              type="button"
              aria-expanded={detailTab === key}
              onClick={() => setDetailTab((active) => (active === key ? null : key))}
              className={cn(
                "inline-flex items-center gap-1 rounded-md px-2.5 py-1.5 text-xs",
                detailTab === key
                  ? "bg-accent/10 text-accent"
                  : "text-text-secondary hover:text-text-primary",
              )}
            >
              <Icon className="h-3.5 w-3.5" aria-hidden="true" />
              {label}
            </button>
          ))}
          <span className="ml-auto text-[11px] text-text-secondary">
            {result.row_count.toLocaleString()} dòng
            {result.latency_ms != null && ` · ${result.latency_ms} ms`}
          </span>
        </div>

        {detailTab && (
          <div className="p-3">
            {detailTab === "table" && (
              <TablePanel columns={result.columns} rows={result.rows} />
            )}
            {detailTab === "sql" && (
              <SqlPanel sql={result.generated_sql} guardStatus={result.guard_status} />
            )}
            {detailTab === "check" && (
              <ul className="list-disc space-y-1 pl-5 text-sm text-text-primary">
                {verificationLines.map((line, index) => (
                  <li key={index}>{line}</li>
                ))}
              </ul>
            )}
          </div>
        )}
      </section>

      <ActionBar
        result={result}
        streaming={false}
        canRun
        onRun={onRetry}
        onStop={() => {}}
      />
    </div>
  );
}
