#!/usr/bin/env bash
# Apply Iceberg JDBC Catalog schema grants to an existing PostgreSQL volume.

set -euo pipefail

POSTGRES_CONTAINER="${POSTGRES_CONTAINER:-postgres-db}"
POSTGRES_DB="${POSTGRES_DB:-agent4da}"
POSTGRES_USER="${POSTGRES_USER:-bigdata}"
ICEBERG_SCHEMA="${ICEBERG_SCHEMA:-iceberg}"
ICEBERG_DB_USER="${ICEBERG_DB_USER:-bigdata}"

log() {
  echo "[init_iceberg_schema] $*"
}

log "Applying schema ${ICEBERG_SCHEMA} on ${POSTGRES_CONTAINER}/${POSTGRES_DB}"

docker exec -i "${POSTGRES_CONTAINER}" \
  psql -v ON_ERROR_STOP=1 -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" \
  -c "CREATE SCHEMA IF NOT EXISTS ${ICEBERG_SCHEMA};" \
  -c "ALTER SCHEMA ${ICEBERG_SCHEMA} OWNER TO ${ICEBERG_DB_USER};" \
  -c "GRANT USAGE, CREATE ON SCHEMA ${ICEBERG_SCHEMA} TO ${ICEBERG_DB_USER};" \
  -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ${ICEBERG_SCHEMA} TO ${ICEBERG_DB_USER};" \
  -c "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ${ICEBERG_SCHEMA} TO ${ICEBERG_DB_USER};" \
  -c "ALTER DEFAULT PRIVILEGES IN SCHEMA ${ICEBERG_SCHEMA} GRANT ALL PRIVILEGES ON TABLES TO ${ICEBERG_DB_USER};" \
  -c "ALTER DEFAULT PRIVILEGES IN SCHEMA ${ICEBERG_SCHEMA} GRANT ALL PRIVILEGES ON SEQUENCES TO ${ICEBERG_DB_USER};"

log "Done."
